dist: trusty
language: node_js
node_js:
  - "node"
  - "6"
install:
  - npm install
script: npm run build
after_success:
  - npm run-script doc

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: enable-travis-ci
    node: 'node'
