dist: trusty
language: node_js
node_js:
  - 8
  - 6

install: npm install

script: npm run test && npm run build

before_install:
  sudo apt-get install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++

after_success:
  - npm run doc
  - echo 'node_modules' > .gitignore
  - echo $CNAME > CNAME

cache:
  yarn: true
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
    node: '8'
