dist: trusty
language: node_js
node_js:
  - "node"
  - "6"
install:
  - npm install
script: npm run build
after_success:
  - npm run-script doc
  - git add -f dist
  - git add -f node_modules/openlayers/dist/ol-debug.js
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: enable-travis-ci
node: 'node'
